%
% THIS IS AN IMPLEMENTATION OF A FUNCTION TO COMPUTE AFFINE TRANSFORMATION
% BETWEEN TWO POINTS
%
% COPYRIGHT BELONGS TO THE AUTHOR OF THIS CODE
%
% AUTHOR : LAKSHMAN KUMAR
% AFFILIATION : UNIVERSITY OF MARYLAND, MARYLAND ROBOTICS CENTER
% EMAIL : LKUMAR93@UMD.EDU
% LINKEDIN : WWW.LINKEDIN.COM/IN/LAKSHMANKUMAR1993
%
% THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THE MIT LICENSE
% THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF
% THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
% 
% BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO
% BE BOUND BY THE TERMS OF THIS LICENSE. THE LICENSOR GRANTS YOU THE RIGHTS
% CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND
% CONDITIONS.
%
function A =  affine_transformation(p1,p2)
G = [  p2(1,1) p2(2,1) 0 0 1 0; 
       0    0   p2(1,1) p2(2,1) 0 1;
       p2(1,2) p2(2,2) 0 0 1 0; 
       0    0   p2(1,2) p2(2,2) 0 1;
       p2(1,3) p2(2,3) 0 0  1 0 ; 
       0    0   p2(1,3) p2(2,3) 0 1;
       ];
   
F = [ p1(1,1);p1(2,1);p1(1,2);p1(2,2);p1(1,3);p1(2,3)] ; 
E = G\F;
A = [E(1) E(2) E(5);
     E(3) E(4) E(6)];
end 


